### ISSUE TITLE
"tags" v "properties"

### ISSUE THREAD

**Issue by vr00n** [perliedman/query-overpass#15]
Anyway we can  remove the **```tags```** in the final output? 
Overpass' web-based geoJSON export just has the properties tag

I tried flattening but that doesn't work.

This would make viz that much more seamless!

Thanks!
Export from QUERY-OVERPASS
```
{
		"type": "Feature",
		"id": "node/291921311",
		"properties": {
			"type": "node",
			"id": 291921311,
			**"tags": {**
				"amenity": "drinking_water",
				"created_by": "Merkaartor 0.11"
			},
			"relations": [],
			"meta": {}
		},
		"geometry": {
			"type": "Point",
			"coordinates": [-73.9556265, 40.7921984]
		}
	}
```

GEOJSON Export from Overpass TURBO

```
    {
      "type": "Feature",
      "id": "node/291921311",
      **"properties"**: {
        "@id": "node/291921311",
        "amenity": "drinking_water",
        "created_by": "Merkaartor 0.11"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -73.9556265,
          40.7921984
        ]
      }
    }
```

**Comment by vr00n** [comment]
Found solution in closed issue - to install from `npm install -g perliedman/query-overpass` works

Perhaps you should update the official npm package?

Thanks!

**Comment by tyrasd** [comment]
For me, the normal `npm install -g query-overpass` also works with the `--flat-properties` option. Did you maybe have an old version of query-overpass installed?

**Comment by vr00n** [comment]
Hey there. Thanks! 
I don't think I had an old version - this was the first time I have used it. 
Maybe I had a typo on args that somehow didn't flatten the file. Saw that you included a version arg - kudos!
