### ISSUE TITLE
query-overpass vs overpass turbo: different resultset for the same query

### ISSUE THREAD

**Issue by petervojtek** [perliedman/query-overpass#2]
Hi,
when I run this query via http://overpass-turbo.eu/, I receive cca 5 ways:
`[out:json];way(around:100,48.1570,17.1326)["name"]["highway"];out;`

However when I run the same query from nodejs via query-overpass, I receive empty resultset.

code:
```
queryOverpass = require('query-overpass');
queryOverpass('[out:json];way(around:100,48.1570,17.1326)["name"]["highway"];out;', function(error, geojson){
	console.log(error);
	console.log(geojson);
});
```

result:
`{ type: 'FeatureCollection', features: [] }`

**Comment by perliedman** [comment]
When I run that query at http://overpass-turbo.eu/, I get this message:

> This query returned no nodes. In OSM, only nodes contain coordinates. For example, a way cannot be displayed without its nodes.
> If this is not what you meant to get, overpass tubo can help you to repair (auto-complete) the query by choosing "repair query" below. Otherwise you can continue to the data.

And even if there are results, they are not shown on the map. Autorepairing gives this query:

```
[out:json];way(around:100,48.1570,17.1326)["name"]["highway"];/*added by auto repair*/(._;>;);/*end of auto repair*/out;
```

Since query-overpass returns GeoJSON, there's no way to do this if there is no geometry in the response from the Overpass API.

**Comment by petervojtek** [comment]
actually the query return result, but the resultset contains only ways, not nodes (hence the message).

When you see the popup in http://overpass-turbo.eu/, just click Show data (or click Data in top right corner) and you will see the data.

**Comment by perliedman** [comment]
Exactly!

Thanks for using query-overpass, btw. The overpass query syntax is a bit weird IMHO, so it's quite easy to do something other than what you intended.

**Comment by iOiurson** [comment]
Hello there !
I'm pretty new to OSM, but i have to use it with NodeJS. I found out about your package, but there's this query i can't seem to get going correctly.

``
[out:json][timeout:25];
{{geocodeArea:Gironde}}->.searchArea;
(
  node["amenity"="recycling"]["recycling_type"="centre"](area.searchArea);
  way["amenity"="recycling"]["recycling_type"="centre"](area.searchArea);
);
out body;
>;
out skel qt;
``

It outputs Error 400, but works perfectly well on http://overpass-turbo.eu/s/f0g...

Is there something i'm missing ?

Thanks a lot !

**Comment by tyrasd** [comment]
@iOiurson  you're not loading the search area before using it to query amenities. You should add `area(3600007405)->.searchArea;` before the first `(` in your query.

Note that the double curly braces are an [extension](http://wiki.openstreetmap.org/wiki/Overpass_turbo/Extended_Overpass_Queries) that only overpass turbo understands, so you have to export your query first (in overpass turbo: export->query->as text) to convert the stuff in `{{}}` to something that Overpass API understands.

**Comment by iOiurson** [comment]
Okay thanks, i am starting to figure it out.

**Comment by iOiurson** [comment]
I still get the 400 error with this string although it's working with overpass:

```
[out:json][timeout:25];area(3600007405)->.gironde;(node['amenity'='recycling']['recycling_type'='centre'](area.gironde);way['amenity'='recycling']['recycling_type'='centre'](area.gironde););out body;>;out skel qt;"
```

What am i doing wrong ?

**Comment by iOiurson** [comment]
My bad, it works, it had nothing to do with the package... Thanks again !
