### ISSUE TITLE
Error with JSONStream

### ISSUE THREAD

**Issue by SrihariThalla** [perliedman/query-overpass#23]
Hi!

Can you help me with this error:

```
Error in ./~/JSONStream/index.js
Module parse failed: /private/var/www/personal/mapbox-maps/node_modules/JSONStream/index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
 @ ./~/query-overpass/index.js 5:17-38
```

Here is what I am working on: [SrihariThalla/mapbox-maps](https://github.com/SrihariThalla/mapbox-maps/blob/647ed900e33f8147b68cd0438d53698690d7ee71/src/components/Overpass.js#L31) [branch: baseline]

Thanks!

**Comment by perliedman** [comment]
Hm, looks like some kinde of Babel misconfiguration.

If you check the file in question (https://github.com/dominictarr/JSONStream/blob/master/index.js), you can see that line 1 does indeed start with a `#` character, a hashbang (`#!`) more precisely.

AFAIK this is valid in Node, but perhaps Babel will have to be configured some special way to alllow it.

**Comment by Semigradsky** [comment]
I see that hasbang was removed in https://github.com/dominictarr/JSONStream/commit/debb492597e1332318798bdd9802f36c21034151. So this issue can be closed.

**Comment by SrihariThalla** [comment]
Finally!
