### ISSUE TITLE
timeout handling

### ISSUE THREAD

**Issue by yanngv29** [perliedman/query-overpass#27]
hi! 
i got this error yesterday when using query-overpass : 

Error: connect ETIMEDOUT 136.243.42.136:80

at Object.exports._errnoException (util.js:1022:11)
at exports._exceptionWithHostPort (util.js:1045:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)

136.243.42.136 is the overpass IP.

i my own code i trap errors but this one crash my node.js server.

it's seems to me that there a missing 

```
            .on('error', function(err) {
              cb(err);
            })
```

in the index.js : 

```
  if (!global.window) {
        r = request.post(options.overpassUrl || 'http://overpass-api.de/api/interpreter', reqOptions);
        r.on('response', function(response) {
              //some code
        }
        //here missing code ? 
```

best regards ,

Yann

**Comment by perliedman** [comment]
Fixed in 746912fde15b971376805f30557fa2a70adb72fc.
