### ISSUE TITLE
Generate flat GeoJSON properties

### ISSUE THREAD

**Issue by tyrasd** [perliedman/query-overpass#3]
Using osmtogeojson's [flatProperties](https://www.npmjs.com/package/osmtogeojson#api) option would make the resulting geojson more useful by removing the nested geojson property structure (tags, meta, etc.), thus making it more easily processable by other software and tools. (FlatProperties is even the default when using osmtogeojson as a [cli](https://www.npmjs.com/package/osmtogeojson#usage) tool, but not when using the API directly).

**Comment by perliedman** [comment]
Sorry for not commenting on this before. It makes total sense.

Anyway, now closed by #4, if I understand correctly.
