### ISSUE TITLE
Recent minor release of JSONStream (1.3.2 -> 1.3.3) broke query-overpass app

### ISSUE THREAD

**Issue by vnugent** [perliedman/query-overpass#33]
My React app just stopped working this week. It seems the cause is related to recent release of JSONStream from 1.3.2 to 1.3.3.

```
ModuleNotFoundError
Could not find module in path: 'JSONStream' relative to '/node_modules/query-overpass/index.js'
▶ 10 stack frames were collapsed.
evaluate
/src/Castles.js:3:17
  1 | import React from "react";
  2 | import { GeoJSON } from "react-leaflet";
> 3 | const overpass = require("query-overpass");
```

**Comment by perliedman** [comment]
Hi,
I have updated the dependency to 1.3.5 with tests still passing, so I guess this must have been some temporary glitch.

Closing this now, feel free to drop a comment if you think I should re-open.
