### ISSUE TITLE
Way queries return empty featureCollection

### ISSUE THREAD

**Issue by wboykinm** [perliedman/query-overpass#9]
### Problem

I'm trying to get components of the road network within a bbox, and instead I get an empty FeatureCollection.

### Script:

```js
var bBox = '(41.143501411390766,-88.857421875,42.474122772511485,-86.92657470703125)';

overpass('[out:json];way[highway="secondary"]' + bBox + ';out;', function(err, data) {
  if (err) {
    console.log('Unknown Error');
    return;
  }
  fs.writeFile(outFile, JSON.stringify(data) , 'utf-8');
}, {
  flatProperties: true
});
```

. . . and `outFile` is `{"type":"FeatureCollection","features":[]}`. 

__However__, if I replace `way[highway="secondary"]` with `node[amenity=drinking_water]`, then I get [exactly the right response](http://geojson.io/#id=gist:wboykinm/c44e1949b4ba3ac8e7e7&map=9/41.9163/-88.0308)

### Suspicions:

- I screwed up the API invocation (The query itself [works on overpass-turbo](http://overpass-turbo.eu/s/eHK))
- I'm hitting some volume limit

**Comment by wboykinm** [comment]
AGH. It was the query. I left this out: `(._;>;);`

Many apologies. :smiley_cat:

**Comment by perliedman** [comment]
No worries, been there myself a couple of times! The overpass query language is a bit cryptic, IMHO.
